name: toprak_rehberi
description: "A Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


#  --------------------------- PACKAGES ---------------------------  #
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  carousel_slider: ^5.0.0
  arc_progress_bar_new: ^1.0.4
  percent_indicator: ^4.2.2
  fl_chart: ^0.68.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.0.8
  shared_preferences: ^2.3.2
  jwt_decoder: ^2.0.1
  flutter_svg: ^2.0.10+1
  turkish: ^0.2.1
  shimmer: ^3.0.0


  # Icons
  cupertino_icons: ^1.0.6
  get: ^4.6.6




# State Management
get: ^4.6.5
get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.14.0


flutter_icons:
  image_path: "assets/icons/icon.png"
  #image_path_android: "assets/images/android/icon.png"
  #image_path_ios: "assets/images/ios/icon.png"
  android: true
  ios: true



flutter:


  uses-material-design: true


  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/products/
    - assets/scores/
    - assets/land_types/
    - .env
