name: toprak_rehberi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


#  --------------------------- PACKAGES ---------------------------  #
dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  carousel_slider: ^4.2.1
  arc_progress_bar_new: ^1.0.4
  percent_indicator: ^4.2.2
  syncfusion_flutter_charts: ^26.2.8
  syncfusion_flutter_gauges: ^26.2.8
  fl_chart: ^0.68.0

  # Icons
  cupertino_icons: ^1.0.6
  get: ^4.6.6

# State Management
get: ^4.6.5
get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/products/
