import 'package:toprak_rehberi/models/product/product.dart';
import 'package:toprak_rehberi/utils/constants/image_strings.dart';

// List of harvested products
final List<Product> harvestedProductsList = [
  Product(
    productName: 'Ayçiçeği',
    progressPercentage: 1,
    fieldName: 'Bahçe 3',
    imagePath: TImages.sunflower,
    plantingDate: '3 Mart 2024',
    harvestDate: '12 Ocak 2025',
    isHarvested: true,
    area: 300,
    score: 3,
  ),
  Product(
    productName: 'Domates',
    progressPercentage: 1,
    fieldName: 'Bağ 2',
    imagePath: TImages.tomato,
    plantingDate: '15 Mayıs 2023',
    harvestDate: '21 Haziran 2024',
    isHarvested: true,
    area: 500,
    score: 4,
  ),
  Product(
    productName: 'Patlıcan',
    progressPercentage: 1,
    fieldName: 'Tarla 2',
    imagePath: TImages.eggplant,
    plantingDate: '1 Nisan 2023',
    harvestDate: '5 Mart 2024',
    isHarvested: true,
    area: 350,
    score: 1,
  ),
  Product(
    productName: 'Patates',
    progressPercentage: 1,
    fieldName: 'Bahçe 1',
    imagePath: TImages.potato,
    plantingDate: '20 Nisan 2023',
    harvestDate: '5 Haziran 2024',
    isHarvested: true,
    area: 450,
    score: 5,
  ),
  Product(
    productName: 'Elma',
    progressPercentage: 1,
    fieldName: 'Tarla 1',
    imagePath: TImages.apple,
    plantingDate: '10 Mayıs 2023',
    harvestDate: '2 Şubat 2024',
    isHarvested: true,
    area: 400,
    score: 2,
  ),
  Product(
    productName: 'Üzüm',
    progressPercentage: 1,
    fieldName: 'Arazi 1',
    imagePath: TImages.grape,
    plantingDate: '25 Nisan 2023',
    harvestDate: '16 Ekim 2023',
    isHarvested: true,
    area: 350,
    score: 4,
  ),
];

// List of planted products (not yet harvested)
final List<Product> plantedProductsList = [
  Product(
    productName: 'Üzüm',
    progressPercentage: 0.124,
    fieldName: 'Arazi 1',
    imagePath: TImages.grape,
    plantingDate: '2 Mayıs 2024',
    harvestDate: '14 Nisan 2025',
    area: 350,
  ),
  Product(
    productName: 'Patates',
    progressPercentage: 0.714,
    fieldName: 'Arazi 3',
    imagePath: TImages.potato,
    plantingDate: '15 Nisan 2024',
    harvestDate: '21 Aralık 2025',
    area: 450,
  ),
  Product(
    productName: 'Soğan',
    progressPercentage: 0.574,
    fieldName: 'Tarla 2',
    imagePath: TImages.onion,
    plantingDate: '20 Mart 2024',
    harvestDate: '5 Mart 2025',
    area: 300,
  ),
  Product(
    productName: 'Buğday',
    progressPercentage: 0.34,
    fieldName: 'Bahçe 1',
    imagePath: TImages.wheat,
    plantingDate: '10 Mayıs 2024',
    harvestDate: '5 Haziran 2025',
    area: 400,
  ),
  Product(
    productName: 'Elma',
    progressPercentage: 0.0445,
    fieldName: 'Tarla 1',
    imagePath: TImages.apple,
    plantingDate: '5 Mayıs 2023',
    harvestDate: '2 Şubat 2024',
    area: 400,
  ),
  Product(
    productName: 'Havuç',
    progressPercentage: 0.444,
    fieldName: 'Arazi 1',
    imagePath: TImages.carrot,
    plantingDate: '15 Nisan 2024',
    harvestDate: '1 Mayıs 2025',
    area: 350,
  ),
];
